[build]
  command = "npm install && npm run build"
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["puppeteer-chromium-resolver", "express", "import-fresh"]